export const readerFixtureBook = {
  id: "reader-e2e-fixture",
  title: "Reader Fixture",
  czechTitle: "Lokální testovací manga",
  aliases: ["Reader E2E Fixture"],
  author: "Manga Reader",
  description: "Stabilní lokální obsah pro browser regresní testy čtečky.",
  genres: ["Test"],
  year: "2026",
  status: "Test",
  license: "Lokální fixture",
  source: "local" as const,
  accent: "#9e252d",
  accentSoft: "#f9dcdc",
  volumes: [{
    id: "reader-fixture-no-volume",
    number: 100000,
    sortKey: 100000,
    displayLabel: "BEZ SVAZKU",
    confirmed: false,
    title: "Kapitoly bez svazku",
    year: "2026",
    chapters: [73, 73.1, 73.2, 364.5].map((number) => ({
      id: `reader-fixture-chapter-${number}`,
      number,
      label: String(number),
      title: `Test kapitoly ${number}`,
      pages: 4,
      language: "cs",
    })),
  }],
  localPages: [
    { name: "Fixture 1", url: "/reader-fixtures/missing.webp", fallbackUrl: "/art/manga-reader-hero-v2.png?fixture=1" },
    { name: "Fixture 2", url: "/reader-fixtures/page-portrait.svg?fixture=2" },
    { name: "Fixture 3", url: "/manga-reader-local-icon.png?fixture=3" },
    { name: "Fixture 4", url: "/art/manga-reader-hero-v2.png?fixture=4" },
  ],
};
